
#ifndef GPIO_PIN_TIMSPM0_H
#define GPIO_PIN_TIMSPM0_H

#include <stdint.h>

#include "soc.h"

#ifdef DEVICE_TIMSPM0

#define GPIO_SOC_IOMUX_INVALID UINT32_MAX

typedef enum hwGPIO_Pin_t
{
  hwGPIO_Pin_NC = -1,

  hwGPIO_Pin_A0 = 0,
  hwGPIO_Pin_A1,
  hwGPIO_Pin_A2,
  hwGPIO_Pin_A3,
  hwGPIO_Pin_A4,
  hwGPIO_Pin_A5,
  hwGPIO_Pin_A6,
  hwGPIO_Pin_A7,
  hwGPIO_Pin_A8,
  hwGPIO_Pin_A9,
  hwGPIO_Pin_A10,
  hwGPIO_Pin_A11,
  hwGPIO_Pin_A12,
  hwGPIO_Pin_A13,
  hwGPIO_Pin_A14,
  hwGPIO_Pin_A15,
  hwGPIO_Pin_A16,
  hwGPIO_Pin_A17,
  hwGPIO_Pin_A18,
  hwGPIO_Pin_A19,
  hwGPIO_Pin_A20,
  hwGPIO_Pin_A21,
  hwGPIO_Pin_A22,
  hwGPIO_Pin_A23,
  hwGPIO_Pin_A24,
  hwGPIO_Pin_A25,
  hwGPIO_Pin_A26,
  hwGPIO_Pin_A27,
  hwGPIO_Pin_A28,
  hwGPIO_Pin_A29,
  hwGPIO_Pin_A30,
  hwGPIO_Pin_A31,

  hwGPIO_Pin_B0,
  hwGPIO_Pin_B1,
  hwGPIO_Pin_B2,
  hwGPIO_Pin_B3,
  hwGPIO_Pin_B4,
  hwGPIO_Pin_B5,
  hwGPIO_Pin_B6,
  hwGPIO_Pin_B7,
  hwGPIO_Pin_B8,
  hwGPIO_Pin_B9,
  hwGPIO_Pin_B10,
  hwGPIO_Pin_B11,
  hwGPIO_Pin_B12,
  hwGPIO_Pin_B13,
  hwGPIO_Pin_B14,
  hwGPIO_Pin_B15,
  hwGPIO_Pin_B16,
  hwGPIO_Pin_B17,
  hwGPIO_Pin_B18,
  hwGPIO_Pin_B19,
  hwGPIO_Pin_B20,
  hwGPIO_Pin_B21,
  hwGPIO_Pin_B22,
  hwGPIO_Pin_B23,
  hwGPIO_Pin_B24,
  hwGPIO_Pin_B25,
  hwGPIO_Pin_B26,
  hwGPIO_Pin_B27,
  hwGPIO_Pin_B28,
  hwGPIO_Pin_B29,
  hwGPIO_Pin_B30,
  hwGPIO_Pin_B31,

  hwGPIO_Pin_C0,
  hwGPIO_Pin_C1,
  hwGPIO_Pin_C2,
  hwGPIO_Pin_C3,
  hwGPIO_Pin_C4,
  hwGPIO_Pin_C5,
  hwGPIO_Pin_C6,
  hwGPIO_Pin_C7,
  hwGPIO_Pin_C8,
  hwGPIO_Pin_C9,
  hwGPIO_Pin_C10,
  hwGPIO_Pin_C11,
  hwGPIO_Pin_C12,
  hwGPIO_Pin_C13,
  hwGPIO_Pin_C14,
  hwGPIO_Pin_C15,
  hwGPIO_Pin_C16,
  hwGPIO_Pin_C17,
  hwGPIO_Pin_C18,
  hwGPIO_Pin_C19,
  hwGPIO_Pin_C20,
  hwGPIO_Pin_C21,
  hwGPIO_Pin_C22,
  hwGPIO_Pin_C23,
  hwGPIO_Pin_C24,
  hwGPIO_Pin_C25,
  hwGPIO_Pin_C26,
  hwGPIO_Pin_C27,
  hwGPIO_Pin_C28,
  hwGPIO_Pin_C29,

  hwGPIO_Pin_MAX
} hwGPIO_Pin;

typedef enum hwGPIO_Int_Pin_t
{
  hwGPIO_Int_Pin_NC = -1,

  hwGPIO_Int_Pin_A0 = 0,
  hwGPIO_Int_Pin_A1,
  hwGPIO_Int_Pin_A2,
  hwGPIO_Int_Pin_A3,
  hwGPIO_Int_Pin_A4,
  hwGPIO_Int_Pin_A5,
  hwGPIO_Int_Pin_A6,
  hwGPIO_Int_Pin_A7,
  hwGPIO_Int_Pin_A8,
  hwGPIO_Int_Pin_A9,
  hwGPIO_Int_Pin_A10,
  hwGPIO_Int_Pin_A11,
  hwGPIO_Int_Pin_A12,
  hwGPIO_Int_Pin_A13,
  hwGPIO_Int_Pin_A14,
  hwGPIO_Int_Pin_A15,
  hwGPIO_Int_Pin_A16,
  hwGPIO_Int_Pin_A17,
  hwGPIO_Int_Pin_A18,
  hwGPIO_Int_Pin_A19,
  hwGPIO_Int_Pin_A20,
  hwGPIO_Int_Pin_A21,
  hwGPIO_Int_Pin_A22,
  hwGPIO_Int_Pin_A23,
  hwGPIO_Int_Pin_A24,
  hwGPIO_Int_Pin_A25,
  hwGPIO_Int_Pin_A26,
  hwGPIO_Int_Pin_A27,
  hwGPIO_Int_Pin_A28,
  hwGPIO_Int_Pin_A29,
  hwGPIO_Int_Pin_A30,
  hwGPIO_Int_Pin_A31,

  hwGPIO_Int_Pin_B0,
  hwGPIO_Int_Pin_B1,
  hwGPIO_Int_Pin_B2,
  hwGPIO_Int_Pin_B3,
  hwGPIO_Int_Pin_B4,
  hwGPIO_Int_Pin_B5,
  hwGPIO_Int_Pin_B6,
  hwGPIO_Int_Pin_B7,
  hwGPIO_Int_Pin_B8,
  hwGPIO_Int_Pin_B9,
  hwGPIO_Int_Pin_B10,
  hwGPIO_Int_Pin_B11,
  hwGPIO_Int_Pin_B12,
  hwGPIO_Int_Pin_B13,
  hwGPIO_Int_Pin_B14,
  hwGPIO_Int_Pin_B15,
  hwGPIO_Int_Pin_B16,
  hwGPIO_Int_Pin_B17,
  hwGPIO_Int_Pin_B18,
  hwGPIO_Int_Pin_B19,
  hwGPIO_Int_Pin_B20,
  hwGPIO_Int_Pin_B21,
  hwGPIO_Int_Pin_B22,
  hwGPIO_Int_Pin_B23,
  hwGPIO_Int_Pin_B24,
  hwGPIO_Int_Pin_B25,
  hwGPIO_Int_Pin_B26,
  hwGPIO_Int_Pin_B27,
  hwGPIO_Int_Pin_B28,
  hwGPIO_Int_Pin_B29,
  hwGPIO_Int_Pin_B30,
  hwGPIO_Int_Pin_B31,

  hwGPIO_Int_Pin_C0,
  hwGPIO_Int_Pin_C1,
  hwGPIO_Int_Pin_C2,
  hwGPIO_Int_Pin_C3,
  hwGPIO_Int_Pin_C4,
  hwGPIO_Int_Pin_C5,
  hwGPIO_Int_Pin_C6,
  hwGPIO_Int_Pin_C7,
  hwGPIO_Int_Pin_C8,
  hwGPIO_Int_Pin_C9,
  hwGPIO_Int_Pin_C10,
  hwGPIO_Int_Pin_C11,
  hwGPIO_Int_Pin_C12,
  hwGPIO_Int_Pin_C13,
  hwGPIO_Int_Pin_C14,
  hwGPIO_Int_Pin_C15,
  hwGPIO_Int_Pin_C16,
  hwGPIO_Int_Pin_C17,
  hwGPIO_Int_Pin_C18,
  hwGPIO_Int_Pin_C19,
  hwGPIO_Int_Pin_C20,
  hwGPIO_Int_Pin_C21,
  hwGPIO_Int_Pin_C22,
  hwGPIO_Int_Pin_C23,
  hwGPIO_Int_Pin_C24,
  hwGPIO_Int_Pin_C25,
  hwGPIO_Int_Pin_C26,
  hwGPIO_Int_Pin_C27,
  hwGPIO_Int_Pin_C28,
  hwGPIO_Int_Pin_C29,

  hwGPIO_Int_Pin_MAX
} hwGPIO_Int_Pin;

GPIO_Regs* GPIO_Map_Soc_Port_Base(hwGPIO_Pin pin);
GPIO_Regs* GPIO_Map_Soc_Int_Port_Base(hwGPIO_Int_Pin pin);
uint32_t GPIO_Map_Soc_Pin_Mask(hwGPIO_Pin pin);
uint32_t GPIO_Map_Soc_Int_Pin_Mask(hwGPIO_Int_Pin pin);
hwGPIO_Int_Pin GPIO_Map_Int_Pin_By_Mask(GPIO_Regs* portBase, uint32_t intMask);
uint32_t GPIO_Map_Soc_Pin_IOMUX(hwGPIO_Pin pin);
uint32_t GPIO_Map_Soc_Int_Pin_IOMUX(hwGPIO_Int_Pin pin);

#endif // DEVICE_TIMSPM0

#endif //GPIO_PIN_TIMSPM0_H
