#pragma once

#define PICO_ON_DEVICE 1
#define PICO_NO_HARDWARE 0
#define PICO_BUILD 1

#define PICO_PLATFORM "rp2040"
#define PICO_RP2040 1

#define PICO_BOARD "pico"
#define PICO_TARGET_NAME "firmware"

#define PICO_FLASH_SIZE_BYTES (2 * 1024 * 1024)
#define PICO_FLASH_SPI_CLKDIV 2

#define PICO_DEFAULT_SYS_CLK_FREQ 125000000
#define PICO_DEFAULT_LED_PIN 25

#define PICO_DEFAULT_UART 0
#define PICO_DEFAULT_UART_TX_PIN 0
#define PICO_DEFAULT_UART_RX_PIN 1

#define PICO_STDIO_UART 1
#define PICO_STDIO_USB 0

#define PICO_USE_BLOCKED_RAM 0
#define PICO_PANIC_FUNCTION panic

#define PARAM_ASSERTIONS_ENABLED_ALL 0
#define PARAM_ASSERTIONS_ENABLED_HARDWARE 0

#define PICO_RUNTIME_NO_INIT_BOOTROM_RESET 1
#define PICO_RUNTIME_NO_INIT_PER_CORE_BOOTROM_RESET 1
#define PICO_RUNTIME_NO_INIT_PER_CORE_H3_IRQ_REGISTERS 1
#define PICO_RUNTIME_NO_INIT_PER_CORE_ENABLE_COPROCESSORS 1
//#define PICO_RUNTIME_NO_INIT_INSTALL_RAM_VECTOR_TABLE 1
#define PICO_RUNTIME_SKIP_INIT_INSTALL_RAM_VECTOR_TABLE 1
#define PICO_RUNTIME_NO_INIT_DEFAULT_ALARM_POOL 1

// 刪掉這些 NO_INIT
// #define PICO_RUNTIME_NO_INIT_EARLY_RESETS 1
// #define PICO_RUNTIME_NO_INIT_USB_POWER_DOWN 1
// #define PICO_RUNTIME_NO_INIT_POST_CLOCK_RESETS 1
// #define PICO_RUNTIME_NO_INIT_RP2040_GPIO_IE_DISABLE 1
// #define PICO_RUNTIME_NO_INIT_SPIN_LOCKS_RESET 1

// 改成 SKIP_INIT
#define PICO_RUNTIME_SKIP_INIT_EARLY_RESETS 1
#define PICO_RUNTIME_SKIP_INIT_USB_POWER_DOWN 1
#define PICO_RUNTIME_SKIP_INIT_POST_CLOCK_RESETS 1
#define PICO_RUNTIME_SKIP_INIT_RP2040_GPIO_IE_DISABLE 1
#define PICO_RUNTIME_SKIP_INIT_SPIN_LOCKS_RESET 1