
#ifndef DISPLAY_CONFIG_H
#define DISPLAY_CONFIG_H

//rp2040
/*
#define CONFIG_DISPLAY_INVERTED
#define CONFIG_DISPLAY_ST7735
#define CONFIG_ST77XX_SPI_INDEX hwSPI_Index_1
#define CONFIG_ST77XX_SPI_CLOCK 100000
#define CONFIG_ST77XX_CS_PN hwGPIO_Pin_9
#define CONFIG_ST77XX_DC_PN hwGPIO_Pin_8
#define CONFIG_ST77XX_RST_PN hwGPIO_Pin_12
#define CONFIG_DISPLAY_BACKLIGHT_PN hwGPIO_Pin_25
*/

#endif //DISPLAY_CONFIG_H