
#ifndef DRIVER_CONFIG_H
#define DRIVER_CONFIG_H

#define CONFIG_SUPPORT_INTERNET

#define CONFIG_ETHERNET_ONBOARD
#define CONFIG_ETHERNET_CHECKSUM_BY_HARDWARE

//#define CONFIG_ETHERNET_DM9051

#define CONFIG_LOG_UART_INDEX hwUART_Index_0 //tivac stm32u5
//#define CONFIG_LOG_UART_INDEX hwUART_Index_1
//#define CONFIG_LOG_UART_INDEX hwUART_Index_2 //stm32h7

#endif //DRIVER_CONFIG_H