
#ifndef LWIP_CONFIG_H
#define LWIP_CONFIG_H

#define CONFIG_LWIP_HEAP_SIZE 16*1024
#define CONFIG_LWIP_NUM_NETCONN 20
#define CONFIG_LWIP_NUM_PBUF 20
#define CONFIG_LWIP_NUM_TCP_PCB 20
#define CONFIG_LWIP_NUM_TCP_PCB_LISTEN 20
#define CONFIG_LWIP_NUM_TCP_PCB_SEG 20
#define CONFIG_LWIP_NUM_UDP_PCB 10
#define CONFIG_LWIP_PBUF_POOL_SIZE 10

#endif //LWIP_CONFIG_H