
#ifndef NFC_CONFIG_H
#define NFC_CONFIG_H

#define CONFIG_M24SR_I2C_INDEX hwI2C_Index_1

#define CONFIG_NFC_READER_DEVICE_ST25R95
//#define CONFIG_NFC_READER_DEVICE_ST25R3916B
// for h7 nucleo series
/*
#define CONFIG_ST25R95_GPIO_IRQ_PIN          hwGPIO_Pin_F15
#define CONFIG_ST25R95_GPIO_CS_PIN           hwGPIO_Pin_D14
#define CONFIG_ST25R95_GPIO_INTERFACE_PIN    hwGPIO_Pin_D15
*/
#define CONFIG_NFC_TYPE_EMPTY_SUPPORT 1
#define CONFIG_NFC_TYPE_FLAT_SUPPORT 1
#define CONFIG_NFC_TYPE_RTD_DEVICE_INFO_SUPPORT 1
#define CONFIG_NFC_TYPE_RTD_TEXT_SUPPORT 1
#define CONFIG_NFC_TYPE_RTD_URI_SUPPORT 1
#define CONFIG_NFC_TYPE_RTD_AAR_SUPPORT 1
#define CONFIG_NFC_TYPE_RTD_WLC_SUPPORT 1
#define CONFIG_NFC_TYPE_RTD_WPCWLC_SUPPORT 1
#define CONFIG_NFC_TYPE_RTD_TNEP_SUPPORT 1
#define CONFIG_NFC_TYPE_MEDIA_SUPPORT 1
#define CONFIG_NFC_TYPE_BLUETOOTH_SUPPORT 1
#define CONFIG_NFC_TYPE_VCARD_SUPPORT 1
#define CONFIG_NFC_TYPE_WIFI_SUPPORT 1
#define CONFIG_NDEF_DEBUG_SUPPORT 1
#define CONFIG_NDEF_DYNAMIC_MEMORY_SUPPORT 1

#endif //NFC_CONFIG_H