
#ifndef SENSOR_CONFIG_H
#define SENSOR_CONFIG_H

#define CONFIG_HTS221_I2C_INDEX hwI2C_Index_1

#define CONFIG_VL53L0X_I2C_INDEX hwI2C_Index_1

#define CONFIG_VL53L1X_POWER_PIN hwGPIO_Pin_E15
#define CONFIG_VL53L1X_I2C_INDEX hwI2C_Index_1

#define CONFIG_VL53L4CD_POWER_PIN hwGPIO_Pin_E14
#define CONFIG_VL53L4CD_I2C_INDEX hwI2C_Index_1

#endif //SENSOR_CONFIG_H